name: Snyk Code Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:

  snyk-code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup Environment 
        uses: snyk/actions/setup@master
        uses: snyk/actions/maven@master
        
      - name: Snyk Scan (code)
        run: snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
