name: Snyk
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  snyk-code-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: snyk test (code)
        run: snyk code test --org=b5ec9e60-ec0e-4bd6-8ad4-85cbe844e8ab
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
