name: Snyk Code Scan

on:
  push:
    branches: 
      - main
      - boosef-snyk-patch-*

jobs:
  snyk-code-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: |
          curl -sSL https://snyk.io/install | bash

      - name: Configure Snyk
        run: snyk config set token ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code Scan
        run: snyk code test
