name: Snyk Code Scan

on:
  push:
    branches: 
      - main
      - boosef-snyk-patch-*

jobs:
  snyk-code-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: |
          wget -O snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/

      - name: Configure Snyk
        run: | 
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk config get api
          snyk code test
          
