name: Snyk Code Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: 
      - main
      - 'boosef-patch-*'
jobs:
  snyk-code-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Snyk Scan (code)
      run: snyk code test -d --org={{ secrets.SNYK_ORG_ID }}
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
